from . import collection_rule
from . import adjustment_type
from . import payment_state
from . import payment_state_rpc
from . import payment_state_contable_justification_wizard
from . import payment_state_cron
from . import payment_state_attachment
from . import ftth_client_service_ext
from . import res_partner_ext
from . import customer_contract_ext
from . import payment_receipt
from . import receipt_config
from . import uncollectible
from . import collection_invoice
